python:
  - 3.6.1
  - 3.5.1
  - 2.7.14

vtk:
  - 8.1.0

itk:
  - 4.13.0

pin_run_as_build:
  python:
    max_pin: x.x.x
    min_pin: x.x
  vtk: x.x.x
  itk: x.x.x

CONDA_BUILD_SYSROOT:
  - $HOME/MacOSX-SDKs/MacOSX10.9.sdk   # [osx]
