## Program: VMTK
## Language:  Python
## Date:      January 30, 2018
## Version:   1.4

##   Copyright (c) Richard Izzo, Luca Antiga, All rights reserved.
##   See LICENSE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

## Note: this code was contributed by
##       Richard Izzo (Github @rlizzo)
##       University at Buffalo

python:
  - 3.10
  - 3.9
  - 3.8
  - 3.7

vtk:
  - 9.1.*

itk:
  - 5.*

numpy:
  - 1.20

pin_run_as_build:
  python:
    max_pin: x.x.x
    min_pin: x.x
  vtk: x.x.x
  itk: x.x.x

c_compiler:
  - vs2015           # [win]

cxx_compiler:
  - vs2015           # [win]

CONDA_BUILD_SYSROOT:
  - $HOME/MacOSX-SDKs/MacOSX10.9.sdk   # [osx]
