## Program: VMTK
## Language:  Python
## Date:      January 30, 2018
## Version:   1.4

##   Copyright (c) Richard Izzo, Luca Antiga, All rights reserved.
##   See LICENSE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

## Note: this code was contributed by
##       Richard Izzo (Github @rlizzo)
##       University at Buffalo

package:
  name: "vmtk"
  version: "1.4.0"

source:
    path: ../

build:
  number: 1
  features:
    - vc14  # [win and (py35 or py36)]  
  skip:
    - True  # [win and py27]  
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkgconfig              # [unix]
    - cmake 
    - git
    - ninja
    - setuptools             # [win] 
  host:
    - python {{ python }}
    - future
    - vtk {{ vtk }}
    - itk {{ itk }}
    - numpy <=1.13
    - h5py
    - setuptools              # [win]
    - mesa                    # [linux]
    - joblib

  run:
    - python {{ python }}
    - future 
    - vtk {{ vtk }}
    - itk {{ itk }}
    - numpy <=1.13
    - h5py
    - mesa                    # [linux]
    - joblib

test:
  source_files:
    - build/tests/*
  requires:
    - pytest
  commands:
    - pytest ./build/tests/

about:
  home: www.vmtk.org
  license_file: LICENSE
  summary: "vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details."

extra:
  recipe-maintainers:
    -rlizzo
    -lantiga
