## Program: VMTK
## Language:  Python
## Date:      January 30, 2020
## Version:   1.4

##   Copyright (c) Richard Izzo, Luca Antiga, All rights reserved.
##   See LICENSE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

## Note: this code was contributed by
##       Richard Izzo (Github @rlizzo)
##       University at Buffalo

package:
  name: "vmtk"
  version: "1.5.0"

source:
    path: ../

build:
  number: 1
  features:
    - vc14  # [win]  
  
requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - pkgconfig              # [unix]
    - cmake 
    - boost 1.74 # [linux]
    - git
    - ninja
    - setuptools             # [win] 
  host:
    - python {{ python }}
    - vtk {{ vtk }}
    - libitk {{ itk }}
    - libitk-devel {{ itk }}
    - numpy >=1.20
    - h5py
    - tbb-devel
    - llvm
    - setuptools              # [win]
    - joblib

  run:
    - python {{ python }}
    - future 
    - vtk {{ vtk }}
    - libitk {{ itk }}
    - numpy 
    - llvm
    - h5py
    - joblib

test:
  source_files:
    - build/tests/*
  requires:
    - pytest
    - pytest-html
  commands:
    - pytest  {{ environ.get('PYTEST_REPORT', '') }} -vv ./build/tests/

about:
  home: www.vmtk.org
  license_file: LICENSE
  summary: "vmtk - the Vascular Modeling Toolkit. See www.vmtk.org/ for details."
extra:
  recipe-maintainers:
    - ramtingh