## Program: VMTK
## Language:  Python
## Date:      January 10, 2018
## Version:   1.4

##   Copyright (c) Richard Izzo, Luca Antiga, All rights reserved.
##   See LICENCE file for details.

##      This software is distributed WITHOUT ANY WARRANTY; without even
##      the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
##      PURPOSE.  See the above copyright notices for more information.

## Note: this code was contributed by
##       Richard Izzo (Github @rlizzo)
##       University at Buffalo

import pytest
import unittest
import os

@pytest.fixture(scope='function')
def vmtk_scripts():
    allscripts =  [
        'vmtk.vmtkscripts.vmtkactivetubes',
        'vmtk.vmtkscripts.vmtkbifurcationprofiles',
        'vmtk.vmtkscripts.vmtkbifurcationreferencesystems',
        'vmtk.vmtkscripts.vmtkbifurcationsections',
        'vmtk.vmtkscripts.vmtkbifurcationvectors',
        'vmtk.vmtkscripts.vmtkboundarylayer',
        'vmtk.vmtkscripts.vmtkboundaryreferencesystems',
        'vmtk.vmtkscripts.vmtkbranchclipper',
        'vmtk.vmtkscripts.vmtkbranchextractor',
        'vmtk.vmtkscripts.vmtkbranchgeometry',
        'vmtk.vmtkscripts.vmtkbranchmapping',
        'vmtk.vmtkscripts.vmtkbranchmetrics',
        'vmtk.vmtkscripts.vmtkbranchpatching',
        'vmtk.vmtkscripts.vmtkbranchsections',
        'vmtk.vmtkscripts.vmtkcenterlineattributes',
        'vmtk.vmtkscripts.vmtkcenterlinegeometry',
        'vmtk.vmtkscripts.vmtkcenterlineinterpolation',
        'vmtk.vmtkscripts.vmtkcenterlinelabeler',
        'vmtk.vmtkscripts.vmtkcenterlinemerge',
        'vmtk.vmtkscripts.vmtkcenterlinemodeller',
        'vmtk.vmtkscripts.vmtkcenterlineoffsetattributes',
        'vmtk.vmtkscripts.vmtkcenterlineresampling',
        'vmtk.vmtkscripts.vmtkcenterlines',
        'vmtk.vmtkscripts.vmtkcenterlinesections',
        'vmtk.vmtkscripts.vmtkcenterlinesmoothing',
        'vmtk.vmtkscripts.vmtkcenterlineviewer',
        'vmtk.vmtkscripts.vmtkdelaunayvoronoi',
        'vmtk.vmtkscripts.vmtkdistancetocenterlines',
        'vmtk.vmtkscripts.vmtkendpointextractor',
        'vmtk.vmtkscripts.vmtkflowextensions',
        'vmtk.vmtkscripts.vmtkicpregistration',
        'vmtk.vmtkscripts.vmtkimagebinarize',
        'vmtk.vmtkscripts.vmtkimagecast',
        'vmtk.vmtkscripts.vmtkimagecompose',
        'vmtk.vmtkscripts.vmtkimagecurvedmpr',
        'vmtk.vmtkscripts.vmtkimagefeaturecorrection',
        'vmtk.vmtkscripts.vmtkimagefeatures',
        'vmtk.vmtkscripts.vmtkimageinitialization',
        'vmtk.vmtkscripts.vmtkimagemipviewer',
        'vmtk.vmtkscripts.vmtkimagemorphology',
        'vmtk.vmtkscripts.vmtkimagenormalize',
        'vmtk.vmtkscripts.vmtkimageobjectenhancement',
        'vmtk.vmtkscripts.vmtkimageotsuthresholds',
        'vmtk.vmtkscripts.vmtkimagereader',
        'vmtk.vmtkscripts.vmtkimagereslice',
        'vmtk.vmtkscripts.vmtkimageseeder',
        'vmtk.vmtkscripts.vmtkimageshiftscale',
        'vmtk.vmtkscripts.vmtkimagesmoothing',
        'vmtk.vmtkscripts.vmtkimageviewer',
        'vmtk.vmtkscripts.vmtkimagevesselenhancement',
        'vmtk.vmtkscripts.vmtkimagevoipainter',
        'vmtk.vmtkscripts.vmtkimagevoiselector',
        'vmtk.vmtkscripts.vmtkimagewriter',
        'vmtk.vmtkscripts.vmtklevelsetsegmentation',
        'vmtk.vmtkscripts.vmtklineartoquadratic',
        'vmtk.vmtkscripts.vmtklineresampling',
        'vmtk.vmtkscripts.vmtklocalgeometry',
        'vmtk.vmtkscripts.vmtkmarchingcubes',
        'vmtk.vmtkscripts.vmtkmesharrayoperation',
        'vmtk.vmtkscripts.vmtkmeshboundaryinspector',
        'vmtk.vmtkscripts.vmtkmeshbranchclipper',
        'vmtk.vmtkscripts.vmtkmeshclipper',
        'vmtk.vmtkscripts.vmtkmeshconnectivity',
        'vmtk.vmtkscripts.vmtkmeshcutter',
        'vmtk.vmtkscripts.vmtkmeshdatareader',
        'vmtk.vmtkscripts.vmtkmeshextractpointdata',
        'vmtk.vmtkscripts.vmtkmeshlambda2',
        'vmtk.vmtkscripts.vmtkmeshlinearize',
        'vmtk.vmtkscripts.vmtkmeshgenerator',
        'vmtk.vmtkscripts.vmtkmeshmergetimesteps',
        'vmtk.vmtkscripts.vmtkmeshpolyballevaluation',
        'vmtk.vmtkscripts.vmtkmeshprojection',
        'vmtk.vmtkscripts.vmtkmeshreader',
        'vmtk.vmtkscripts.vmtkmeshscaling',
        'vmtk.vmtkscripts.vmtkmeshtetrahedralize',
        'vmtk.vmtkscripts.vmtkmeshtosurface',
        'vmtk.vmtkscripts.vmtkmeshtransform',
        'vmtk.vmtkscripts.vmtkmeshtransformtoras',
        'vmtk.vmtkscripts.vmtkmeshvectorfromcomponents',
        'vmtk.vmtkscripts.vmtkmeshviewer',
        'vmtk.vmtkscripts.vmtkmeshvolume',
        'vmtk.vmtkscripts.vmtkmeshvorticityhelicity',
        'vmtk.vmtkscripts.vmtkmeshwallshearrate',
        'vmtk.vmtkscripts.vmtkmeshwriter',
        'vmtk.vmtkscripts.vmtknetworkeditor',
        'vmtk.vmtkscripts.vmtknetworkextraction',
        'vmtk.vmtkscripts.vmtknetworkwriter',
        'vmtk.vmtkscripts.vmtkparticletracer',
        'vmtk.vmtkscripts.vmtkpathlineanimator',
        'vmtk.vmtkscripts.vmtkpointsplitextractor',
        'vmtk.vmtkscripts.vmtkpointtransform',
        'vmtk.vmtkscripts.vmtkpolyballmodeller',
        'vmtk.vmtkscripts.vmtkpotentialfit',
        'vmtk.vmtkscripts.vmtkpythonscript',
        'vmtk.vmtkscripts.vmtkrenderer',
        'vmtk.vmtkscripts.vmtkrendertoimage',
        'vmtk.vmtkscripts.vmtkrbfinterpolation',
        'vmtk.vmtkscripts.vmtksurfaceappend',
        'vmtk.vmtkscripts.vmtksurfacearraysmoothing',
        'vmtk.vmtkscripts.vmtksurfacearrayoperation',
        'vmtk.vmtkscripts.vmtksurfacebooleanoperation',
        'vmtk.vmtkscripts.vmtksurfacecapper',
        'vmtk.vmtkscripts.vmtksurfacecelldatatopointdata',
        'vmtk.vmtkscripts.vmtksurfacecenterlineprojection',
        'vmtk.vmtkscripts.vmtksurfaceclipper',
        'vmtk.vmtkscripts.vmtksurfacecliploop',
        'vmtk.vmtkscripts.vmtksurfaceconnectivity',
        'vmtk.vmtkscripts.vmtksurfacecurvature',
        'vmtk.vmtkscripts.vmtksurfacedecimation',
        'vmtk.vmtkscripts.vmtksurfacedistance',
        'vmtk.vmtkscripts.vmtksurfaceendclipper',
        'vmtk.vmtkscripts.vmtksurfacekiteremoval',
        'vmtk.vmtkscripts.vmtksurfaceloopextraction',
        'vmtk.vmtkscripts.vmtksurfacemassproperties',
        'vmtk.vmtkscripts.vmtksurfacemodeller',
        'vmtk.vmtkscripts.vmtksurfacenormals',
        'vmtk.vmtkscripts.vmtksurfacepointdatatocelldata',
        'vmtk.vmtkscripts.vmtksurfacepolyballevaluation',
        'vmtk.vmtkscripts.vmtksurfaceprojection',
        'vmtk.vmtkscripts.vmtksurfacereader',
        'vmtk.vmtkscripts.vmtksurfacereferencesystemtransform',
        'vmtk.vmtkscripts.vmtksurfaceregiondrawing',
        'vmtk.vmtkscripts.vmtksurfaceremeshing',
        'vmtk.vmtkscripts.vmtksurfacescaling',
        'vmtk.vmtkscripts.vmtksurfacesmoothing',
        'vmtk.vmtkscripts.vmtksurfacesubdivision',
        'vmtk.vmtkscripts.vmtksurfacetransform',
        'vmtk.vmtkscripts.vmtksurfacetransforminteractive',
        'vmtk.vmtkscripts.vmtksurfacetransformtoras',
        'vmtk.vmtkscripts.vmtksurfacetriangle',
        'vmtk.vmtkscripts.vmtksurfacetomesh',
        'vmtk.vmtkscripts.vmtksurfaceviewer',
        'vmtk.vmtkscripts.vmtksurfacewriter',
        'vmtk.vmtkscripts.vmtksurfmesh',
        'vmtk.vmtkscripts.vmtktetgen',
        'vmtk.vmtkscripts.vmtktetringenerator',
        'vmtk.vmtkscripts.contrib.vmtkboundarylayer2',
        'vmtk.vmtkscripts.contrib.vmtkcenterlinestonumpy',
        'vmtk.vmtkscripts.contrib.vmtkdijkstradistancetopoints',
        'vmtk.vmtkscripts.contrib.vmtkdistancetospheres',
        'vmtk.vmtkscripts.contrib.vmtkentityrenumber',
        'vmtk.vmtkscripts.contrib.vmtkgeodesicsurfaceresolution',
        'vmtk.vmtkscripts.contrib.vmtkimagetonumpy',
        'vmtk.vmtkscripts.contrib.vmtkmeshaddexternallayer',
        'vmtk.vmtkscripts.contrib.vmtkmeshclipcenterlines',
        'vmtk.vmtkscripts.contrib.vmtkmeshmerge',
        'vmtk.vmtkscripts.contrib.vmtkmeshtetrahedralize2',
        'vmtk.vmtkscripts.contrib.vmtkmeshviewer2',
        'vmtk.vmtkscripts.contrib.vmtkmeshwriter2',
        'vmtk.vmtkscripts.contrib.vmtknumpyreader',
        'vmtk.vmtkscripts.contrib.vmtknumpytocenterlines',
        'vmtk.vmtkscripts.contrib.vmtknumpytoimage',
        'vmtk.vmtkscripts.contrib.vmtknumpytosurface',
        'vmtk.vmtkscripts.contrib.vmtknumpywriter',
        'vmtk.vmtkscripts.contrib.vmtksurfaceextractinnercylinder',
        'vmtk.vmtkscripts.contrib.vmtksurfaceresolution',
        'vmtk.vmtkscripts.contrib.vmtksurfacetonumpy',
        'vmtk.vmtkscripts.contrib.vmtksurfacewriter2',
        'vmtk.vmtkscripts.contrib.vmtkthreshold' ]
    return allscripts

def test_import_vmtkScripts(vmtk_scripts):
    import importlib
    print(vmtk_scripts)
    for name in vmtk_scripts:
        assert importlib.import_module(name)

